{"uid":"405e79ecef9921f9","name":"Test to verify that user can complete the pause task with exception","fullName":"tests.scenarios.job.test_job_execution.TestJobExecution#test_complete_pause_task_with_exception","historyId":"f878b7c35a722d0b5fcd23a535517f5f","time":{"start":1734104638392,"stop":1734104638392,"duration":0},"description":"This testcase tests completing the pause task while executing the job","descriptionHtml":"<p>This testcase tests completing the pause task while executing the job</p>\n","status":"skipped","statusMessage":"Skipped: We cannot complete the task with exception when task are paused","statusTrace":"('/home/server1/Documents/platform-api-maint-4.9-changes/tests/scenarios/job/test_job_execution.py', 1456, 'Skipped: We cannot complete the task with exception when task are paused')","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"env_setup","time":{"start":1734094787340,"stop":1734094787340,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"login_fixture","time":{"start":1734094787340,"stop":1734094787555,"duration":215},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"get_facility","time":{"start":1734094787556,"stop":1734094787676,"duration":120},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"select_usecase_fixture","time":{"start":1734094787676,"stop":1734094787784,"duration":108},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"username_to_user_id_mapping","time":{"start":1734094787784,"stop":1734094788037,"duration":253},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"user_group_creation","time":{"start":1734103452585,"stop":1734103453272,"duration":687},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"flush_param_counters","time":{"start":1734104638396,"stop":1734104638396,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"afterStages":[{"name":"flush_param_counters::0","time":{"start":1734104650670,"stop":1734104650670,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"tag","value":"@pytest.mark.skip(reason='We cannot complete the task with exception when task are paused')"},{"name":"tag","value":"complete_pause_task_with_exception"},{"name":"tag","value":"job"},{"name":"tag","value":"scenario"},{"name":"parentSuite","value":"tests.scenarios.job"},{"name":"suite","value":"test_job_execution"},{"name":"subSuite","value":"TestJobExecution"},{"name":"host","value":"ubuntu"},{"name":"thread","value":"590668-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.scenarios.job.test_job_execution"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"job_execution_by","value":"'user_group'"},{"name":"users_list","value":"[]"}],"links":[{"name":"https://app.clickup.com/t/86cukreh9","url":"https://app.clickup.com/t/86cukreh9","type":"link"}],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[],"tags":["scenario","complete_pause_task_with_exception","job","@pytest.mark.skip(reason='We cannot complete the task with exception when task are paused')"]},"source":"405e79ecef9921f9.json","parameterValues":["'user_group'","[]"]}