{"uid":"7f65b6ecc85e4d51","name":"Test to verify that user can complete the pause task with exception","fullName":"tests.scenarios.job.test_job_execution.TestJobExecution#test_complete_pause_task_with_exception","historyId":"f878b7c35a722d0b5fcd23a535517f5f","time":{"start":1733761294064,"stop":1733761294064,"duration":0},"description":"This testcase tests completing the pause task while executing the job","descriptionHtml":"<p>This testcase tests completing the pause task while executing the job</p>\n","status":"skipped","statusMessage":"Skipped: We cannot complete the task with exception when task are paused","statusTrace":"('/home/server1/Downloads/platform-api-develop/tests/scenarios/job/test_job_execution.py', 1422, 'Skipped: We cannot complete the task with exception when task are paused')","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":1,"retriesStatusChange":false,"beforeStages":[{"name":"env_setup","time":{"start":1733752687376,"stop":1733752687376,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"login_fixture","time":{"start":1733752687376,"stop":1733752687642,"duration":266},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"get_facility","time":{"start":1733752687642,"stop":1733752687801,"duration":159},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"select_usecase_fixture","time":{"start":1733752687801,"stop":1733752687918,"duration":117},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"username_to_user_id_mapping","time":{"start":1733752687918,"stop":1733752688451,"duration":533},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"user_group_creation","time":{"start":1733760133164,"stop":1733760133769,"duration":605},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"flush_param_counters","time":{"start":1733761294066,"stop":1733761294066,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"afterStages":[{"name":"flush_param_counters::0","time":{"start":1733761305291,"stop":1733761305291,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"tag","value":"@pytest.mark.skip(reason='We cannot complete the task with exception when task are paused')"},{"name":"tag","value":"complete_pause_task_with_exception"},{"name":"tag","value":"job"},{"name":"tag","value":"scenario"},{"name":"parentSuite","value":"tests.scenarios.job"},{"name":"suite","value":"test_job_execution"},{"name":"subSuite","value":"TestJobExecution"},{"name":"host","value":"ubuntu"},{"name":"thread","value":"53959-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.scenarios.job.test_job_execution"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"job_execution_by","value":"'user_group'"},{"name":"users_list","value":"[]"}],"links":[{"name":"https://app.clickup.com/t/86cukreh9","url":"https://app.clickup.com/t/86cukreh9","type":"link"}],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"43d9cb92a99ceb40","status":"skipped","statusDetails":"Skipped: We cannot complete the task with exception when task are paused","time":{"start":1733499021678,"stop":1733499021678,"duration":0}}],"categories":[],"tags":["scenario","complete_pause_task_with_exception","job","@pytest.mark.skip(reason='We cannot complete the task with exception when task are paused')"]},"source":"7f65b6ecc85e4d51.json","parameterValues":["'user_group'","[]"]}